---

    - name: install unzip, alien
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - alien

    - name: oracle-xe-11 rpm to debian
      shell: alien --to-deb --scripts oracle-xe-11.2.0-1.0.x86_64.rpm chdir=/tmp
